// Generated by CoffeeScript 1.10.0
(function() {
  var Schema, SearchEntry, mongoose;

  mongoose = require("mongoose");

  Schema = mongoose.Schema;

  SearchEntry = new Schema({
    query: String,
    offset: Number,
    date: Date
  });

  module.exports = mongoose.model("SearchEntry", SearchEntry);

}).call(this);
